/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaySongIdRouteImport } from './routes/play/$songId'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySongIdRoute = PlaySongIdRouteImport.update({
  id: '/play/$songId',
  path: '/play/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/play/$songId': typeof PlaySongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/play/$songId': typeof PlaySongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/roadmap': typeof RoadmapRoute
  '/signup': typeof SignupRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/play/$songId': typeof PlaySongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/guide'
    | '/login'
    | '/roadmap'
    | '/signup'
    | '/library'
    | '/play/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/guide'
    | '/login'
    | '/roadmap'
    | '/signup'
    | '/library'
    | '/play/$songId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/guide'
    | '/login'
    | '/roadmap'
    | '/signup'
    | '/_authenticated/library'
    | '/play/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  RoadmapRoute: typeof RoadmapRoute
  SignupRoute: typeof SignupRoute
  PlaySongIdRoute: typeof PlaySongIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$songId': {
      id: '/play/$songId'
      path: '/play/$songId'
      fullPath: '/play/$songId'
      preLoaderRoute: typeof PlaySongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  RoadmapRoute: RoadmapRoute,
  SignupRoute: SignupRoute,
  PlaySongIdRoute: PlaySongIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
